#  _______ _ _   _                                                           
# |__   __(_) | | |        /\                                                
#    | |   _| |_| | ___   /  \   _ __  _ __   ___  _   _ _ __   ___ ___ _ __ 
#    | |  | | __| |/ _ \ / /\ \ | '_ \| '_ \ / _ \| | | | '_ \ / __/ _ \ '__|
#    | |  | | |_| |  __// ____ \| | | | | | | (_) | |_| | | | | (_|  __/ |   
#    |_|  |_|\__|_|\___/_/    \_\_| |_|_| |_|\___/ \__,_|_| |_|\___\___|_|   
#                                                                           
# To modify the plugin messages and to use the plugin in general, 
# I recommend that you have a basic knowledge of MiniMessage.
# Guide: https://docs.adventure.kyori.net/minimessage.html#format
# Spanish Guide: https://gist.github.com/4drian3d/9ccce0ca1774285e38becb09b73728f3
#
# Plugin messages
messages:
  title:
    # Message displayed in case the command is executed without arguments
    without-argument: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <red>You need to enter the title and subtitle arguments.</red>"
    # Message to be sent when executing the /sendtitle command and only the player is specified
    only-player: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <gray>You must enter the title and subtitle after the player's name to send the message correctly.</gray>"
    # Message displayed in case the command is executed with only one argument.
    # In case you want to send a title without a subtitle, 
    # enter the title you want and in the subtitle field add a color <red> for example.
    single-argument: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <gray>You need to enter the title, the subtitle and the separator ';' in orden to send the title.</gray>"
    # Message displayed when the title has been displayed successfully
    successfully: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <green>Title succesfully sended</green>"
    # Message displayed when an error occurs while sending the title
    error: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <dark_red>An error occurred while sending the title. Be sure to use the ';' to separate the title and the subtitle.</dark_red>"
    # Message to send to the player in case he does not have the respective permission.
    no-permission: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <red>You do not have permission to execute this command</red>"
  actionbar:
    # Message displayed when the actionbar has been displayed successfully
    successfully: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <green>Actionbar succesfully sended</green>"
    # Message to send to the player in case he does not have the respective permission.
    no-permission: "<gray>[</gray><gradient:yellow:blue>TitleAnnouncer</gradient><gray>]</gray> <red>You do not have permission to execute this command</red>"
# Plugin sounds
# In the ID field you must enter a valid value from: 
# https://minecraft.fandom.com/wiki/Sounds.json/Java_Edition_values
#sounds:
#  title:
#    enabled: true 
#    id: "entity.experience_orb.pickup"
#  actionbar: 
#    enabled: true
#    id: "entity.experience_orb.pickup"
